// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefactorAI.Backend.Data;

#nullable disable

namespace RefactorAI.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("RefactorAI.Backend.Models.Entities.AiRunResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppliedTechniques")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BenchmarkRunId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiedCodeSmells")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewComplexity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewLinesOfCode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NewMaintainabilityIndex")
                        .HasColumnType("REAL");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkRunId");

                    b.ToTable("AiRunResults");
                });

            modelBuilder.Entity("RefactorAI.Backend.Models.Entities.BenchmarkRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalComplexity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalLinesOfCode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OriginalMaintainabilityIndex")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BenchmarkRuns");
                });

            modelBuilder.Entity("RefactorAI.Backend.Models.Entities.AiRunResult", b =>
                {
                    b.HasOne("RefactorAI.Backend.Models.Entities.BenchmarkRun", null)
                        .WithMany("Results")
                        .HasForeignKey("BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RefactorAI.Backend.Models.Entities.BenchmarkRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
